version: '3.12'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
  


  redis:
    image: redis:7
    ports:
    - "6379:6379"